WellCommerce\Bundle\AttributeBundle\Entity\AttributeValue:
    type: entity
    table: attribute_value
    repositoryClass: WellCommerce\Bundle\AppBundle\Repository\AttributeValueRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToOne:
        attribute:
            targetEntity: WellCommerce\Bundle\AttributeBundle\Entity\Attribute
            fetch: LAZY
            inversedBy: values
            joinColumns:
                attribute_id:
                    referencedColumnName: id
                    onDelete: CASCADE
    manyToMany:
        productAttributeValues:
            targetEntity: WellCommerce\Bundle\ProductBundle\Entity\ProductAttribute
            fetch: LAZY
            mappedBy: attributeValues
