WellCommerce\Bundle\CategoryBundle\Entity\Category:
    type: entity
    cache:
        usage: NONSTRICT_READ_WRITE
    table: category
    repositoryClass: WellCommerce\Bundle\CategoryBundle\Repository\CategoryRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        hierarchy:
            type: integer
            nullable: false
            options:
                default: 0
        enabled:
            type: boolean
            nullable: false
    manyToOne:
        parent:
            targetEntity: WellCommerce\Bundle\CategoryBundle\Entity\Category
            fetch: LAZY
            inversedBy: children
            joinColumns:
                parent_id:
                    referencedColumnName: id
                    onDelete: CASCADE
    oneToMany:
        children:
            targetEntity: WellCommerce\Bundle\CategoryBundle\Entity\Category
            fetch: LAZY
            mappedBy: parent
    manyToMany:
        products:
            targetEntity: WellCommerce\Bundle\ProductBundle\Entity\Product
            fetch: LAZY
            mappedBy: categories
        shops:
            targetEntity: WellCommerce\Bundle\ShopBundle\Entity\ShopInterface
            fetch: LAZY
            joinTable:
                name: shop_category
                joinColumns:
                    -
                        name: category_id
                        nullable: false
                        onDelete: CASCADE
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: shop_id
                        nullable: false
                        onDelete: CASCADE
                        referencedColumnName: id
