WellCommerce\Bundle\CompanyBundle\Entity\Company:
    type: entity
    table: company
    repositoryClass: WellCommerce\Bundle\AppBundle\Repository\CompanyRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    embedded:
        address:
            class: WellCommerce\Bundle\CompanyBundle\Entity\CompanyAddress
            columnPrefix: address_
    fields:
        name:
            type: string
            length: 255
            nullable: false
        shortName:
            type: string
            length: 255
            nullable: false
            column: short_name
