WellCommerce\Bundle\AppBundle\Entity\ProductPhoto:
    type: entity
    table: product_photo
    repositoryClass: WellCommerce\Bundle\AppBundle\Repository\ProductPhotoRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        mainPhoto:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            options:
                default: 0
            column: main_photo
        hierarchy:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
            options:
                default: 0
    manyToOne:
        photo:
            targetEntity: WellCommerce\Bundle\AppBundle\Entity\Media
            fetch: LAZY
            joinColumns:
                photo_id:
                    referencedColumnName: id
        product:
            targetEntity: WellCommerce\Bundle\AppBundle\Entity\Product
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: productPhotos
            joinColumns:
                product_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
