WellCommerce\Bundle\ProductStatusBundle\Entity\ProductStatus:
    type: entity
    cache:
        usage: NONSTRICT_READ_WRITE
    table: product_status
    repositoryClass: WellCommerce\Bundle\ProductStatusBundle\Repository\ProductStatusRepository
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    manyToMany:
        products:
            targetEntity: WellCommerce\Bundle\ProductBundle\Entity\Product
            fetch: LAZY
            mappedBy: statuses
