WellCommerce\Bundle\ReviewBundle\Entity\Review:
    fields:
        id:
            groups:
                - default
                - review
        nick:
            groups:
                - default
                - review
        review:
            groups:
                - default
                - review
        rating:
            groups:
                - default
                - review
        ratingLevel:
            groups:
                - default
                - review
        ratingRecommendation:
            groups:
                - default
                - review
        createdAt:
            groups:
                - default
                - review
        updatedAt:
            groups:
                - default
                - review
    associations:
        product:
            groups:
                - review
    callbacks: {  }
