WellCommerce\Bundle\AttributeBundle\Entity\Attribute\Group:
    type: entity
    table: attribute_group
    repositoryClass: WellCommerce\Bundle\AttributeBundle\Repository\AttributeGroupRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    oneToMany:
        attributes:
            targetEntity: WellCommerce\Bundle\AttributeBundle\Entity\Attribute
            cascade:
                - all
            fetch: LAZY
            mappedBy: attributeGroup
            orphanRemoval: true

