# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

WellCommerce\Bundle\AttributeBundle\Entity\AttributeTranslation:
    type: entity
    table: attribute_translation
    fields:
        name:
            type: string
            length: 255
            nullable: false
