WellCommerce\Bundle\CartBundle\Entity\CartProduct:
    type: entity
    table: cart_product
    repositoryClass: WellCommerce\Bundle\CartBundle\Repository\CartProductRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        quantity:
            type: decimal
            scale: 4
            nullable: false
            precision: 15
    manyToOne:
        cart:
            targetEntity: WellCommerce\Bundle\CartBundle\Entity\Cart
            fetch: LAZY
            inversedBy: products
            joinColumns:
                cart_id:
                    referencedColumnName: id
                    onDelete: CASCADE
        product:
            targetEntity: WellCommerce\Bundle\ProductBundle\Entity\Product
            fetch: LAZY
            joinColumns:
                product_id:
                    referencedColumnName: id
                    onDelete: CASCADE
        attribute:
            targetEntity: WellCommerce\Bundle\ProductBundle\Entity\ProductAttribute
            fetch: LAZY
            joinColumns:
                attribute_id:
                    referencedColumnName: id
                    onDelete: CASCADE
