WellCommerce\Bundle\CurrencyBundle\Entity\CurrencyRate:
    type: entity
    cache:
        usage: NONSTRICT_READ_WRITE
    table: currency_rate
    repositoryClass: WellCommerce\Bundle\CurrencyBundle\Repository\CurrencyRateRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        currencyFrom:
            type: string
            length: 12
            unique: false
            nullable: false
            column: currency_from
        currencyTo:
            type: string
            length: 12
            unique: false
            nullable: false
            column: currency_to
        exchangeRate:
            type: decimal
            scale: 4
            nullable: false
            precision: 15
            column: exchange_rate
