WellCommerce\Bundle\CurrencyBundle\Entity\Currency:
    type: entity
    cache:
        usage: NONSTRICT_READ_WRITE
    table: currency
    repositoryClass: WellCommerce\Bundle\CurrencyBundle\Repository\CurrencyRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        code:
            type: string
            length: 12
            unique: true
            nullable: false
        enabled:
            type: boolean
            nullable: false
            options:
                default: true
