wellcommerce_api:
    resource: "@WellCommerceApiBundle/Resources/config/routing.yml"

wellcommerce_attribute:
    resource: "@WellCommerceAttributeBundle/Resources/config/routing.yml"

wellcommerce_availability:
    resource: "@WellCommerceAvailabilityBundle/Resources/config/routing.yml"

wellcommerce_category:
    resource: "@WellCommerceCategoryBundle/Resources/config/routing.yml"

wellcommerce_contact:
    resource: "@WellCommerceContactBundle/Resources/config/routing.yml"

wellcommerce_currency:
    resource: "@WellCommerceCurrencyBundle/Resources/config/routing.yml"

wellcommerce_deliverer:
    resource: "@WellCommerceDelivererBundle/Resources/config/routing.yml"

wellcommerce_dictionary:
    resource: "@WellCommerceDictionaryBundle/Resources/config/routing.yml"

wellcommerce_distribution:
    resource: "@WellCommerceDistributionBundle/Resources/config/routing.yml"

wellcommerce_layered_navigation:
    resource: "@WellCommerceLayeredNavigationBundle/Resources/config/routing.yml"

wellcommerce_layout:
    resource: "@WellCommerceLayoutBundle/Resources/config/routing.yml"

wellcommerce_locale:
    resource: "@WellCommerceLocaleBundle/Resources/config/routing.yml"

wellcommerce_shop:
    resource: "@WellCommerceShopBundle/Resources/config/routing.yml"

wellcommerce_company:
    resource: "@WellCommerceCompanyBundle/Resources/config/routing.yml"

wellcommerce_coupon:
    resource: "@WellCommerceCouponBundle/Resources/config/routing.yml"

wellcommerce_client:
    resource: "@WellCommerceClientBundle/Resources/config/routing.yml"

wellcommerce_media:
    resource: "@WellCommerceMediaBundle/Resources/config/routing.yml"

wellcommerce_news:
    resource: "@WellCommerceNewsBundle/Resources/config/routing.yml"

wellcommerce_admin:
    resource: "@WellCommerceAdminBundle/Resources/config/routing.yml"

wellcommerce_oauth:
    resource: "@WellCommerceOAuthBundle/Resources/config/routing.yml"

wellcommerce_order:
    resource: "@WellCommerceOrderBundle/Resources/config/routing.yml"

wellcommerce_page:
    resource: "@WellCommercePageBundle/Resources/config/routing.yml"

wellcommerce_payment:
    resource: "@WellCommercePaymentBundle/Resources/config/routing.yml"

wellcommerce_producer:
    resource: "@WellCommerceProducerBundle/Resources/config/routing.yml"

wellcommerce_product:
    resource: "@WellCommerceProductBundle/Resources/config/routing.yml"

wellcommerce_product_status:
    resource: "@WellCommerceProductStatusBundle/Resources/config/routing.yml"

wellcommerce_report:
    resource: "@WellCommerceReportBundle/Resources/config/routing.yml"

wellcommerce_review:
    resource: "@WellCommerceReviewBundle/Resources/config/routing.yml"

wellcommerce_routing:
    resource: "@WellCommerceRoutingBundle/Resources/config/routing.yml"

wellcommerce_search:
    resource: "@WellCommerceSearchBundle/Resources/config/routing.yml"

wellcommerce_shipping:
    resource: "@WellCommerceShippingBundle/Resources/config/routing.yml"

wellcommerce_tax:
    resource: "@WellCommerceTaxBundle/Resources/config/routing.yml"

wellcommerce_theme:
    resource: "@WellCommerceThemeBundle/Resources/config/routing.yml"

wellcommerce_unit:
    resource: "@WellCommerceUnitBundle/Resources/config/routing.yml"

wellcommerce_wishlist:
    resource: "@WellCommerceWishlistBundle/Resources/config/routing.yml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

front.home_page.index:
    path: /
    defaults:
        _controller: 'web.home_page.controller.front:indexAction'

root:
    path: /admin
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: admin.user.index
        permanent: false

remove_trailing_slash:
    path: /{url}
    defaults: { _controller: WellCommerceAppBundle:Redirecting:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]
