# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

imports:
    - { resource: "app/" }
    - { resource: "@WellCommerceAdminBundle/Resources/config/wellcommerce.yml" }
    - { resource: "@WellCommerceApiBundle/Resources/config/wellcommerce.yml" }
    - { resource: "@WellCommerceAttributeBundle/Resources/config/wellcommerce.yml" }
    - { resource: "@WellCommerceAvailabilityBundle/Resources/config/wellcommerce.yml" }
    - { resource: "@WellCommerceCategoryBundle/Resources/config/wellcommerce.yml" }
    - { resource: "@WellCommerceClientBundle/Resources/config/wellcommerce.yml" }
    - { resource: "@WellCommerceCompanyBundle/Resources/config/wellcommerce.yml" }
    - { resource: "@WellCommerceContactBundle/Resources/config/wellcommerce.yml" }
    - { resource: "@WellCommerceCouponBundle/Resources/config/wellcommerce.yml" }
    - { resource: "@WellCommerceCurrencyBundle/Resources/config/wellcommerce.yml" }
    - { resource: "@WellCommerceDelivererBundle/Resources/config/wellcommerce.yml" }
    - { resource: "@WellCommerceDictionaryBundle/Resources/config/wellcommerce.yml" }
    - { resource: "@WellCommerceDistributionBundle/Resources/config/wellcommerce.yml" }
    - { resource: "@WellCommerceDoctrineBundle/Resources/config/wellcommerce.yml" }
    - { resource: "@WellCommerceLayoutBundle/Resources/config/wellcommerce.yml" }
    - { resource: "@WellCommerceLocaleBundle/Resources/config/wellcommerce.yml" }
    - { resource: "@WellCommerceMediaBundle/Resources/config/wellcommerce.yml" }
    - { resource: "@WellCommerceNewsBundle/Resources/config/wellcommerce.yml" }
    - { resource: "@WellCommerceOrderBundle/Resources/config/wellcommerce.yml" }
    - { resource: "@WellCommercePageBundle/Resources/config/wellcommerce.yml" }
    - { resource: "@WellCommercePaymentBundle/Resources/config/wellcommerce.yml" }
    - { resource: "@WellCommerceProducerBundle/Resources/config/wellcommerce.yml" }
    - { resource: "@WellCommerceProductBundle/Resources/config/wellcommerce.yml" }
    - { resource: "@WellCommerceProductStatusBundle/Resources/config/wellcommerce.yml" }
    - { resource: "@WellCommerceReportBundle/Resources/config/wellcommerce.yml" }
    - { resource: "@WellCommerceReviewBundle/Resources/config/wellcommerce.yml" }
    - { resource: "@WellCommerceRoutingBundle/Resources/config/wellcommerce.yml" }
    - { resource: "@WellCommerceSearchBundle/Resources/config/wellcommerce.yml" }
    - { resource: "@WellCommerceShippingBundle/Resources/config/wellcommerce.yml" }
    - { resource: "@WellCommerceShopBundle/Resources/config/wellcommerce.yml" }
    - { resource: "@WellCommerceTaxBundle/Resources/config/wellcommerce.yml" }
    - { resource: "@WellCommerceThemeBundle/Resources/config/wellcommerce.yml" }
    - { resource: "@WellCommerceUnitBundle/Resources/config/wellcommerce.yml" }
    - { resource: "@WellCommerceWishlistBundle/Resources/config/wellcommerce.yml" }

parameters:
    routing_discriminator_map: ~
    fixtures_load_order:
        WellCommerce\Bundle\AdminBundle\DataFixtures\ORM\LoadAdminMenuData: 0
        WellCommerce\Bundle\ThemeBundle\DataFixtures\ORM\LoadThemeData: 10
        WellCommerce\Bundle\CompanyBundle\DataFixtures\ORM\LoadCompanyData: 20
        WellCommerce\Bundle\CurrencyBundle\DataFixtures\ORM\LoadCurrencyData: 30
        WellCommerce\Bundle\LocaleBundle\DataFixtures\ORM\LoadLocaleData: 40
        WellCommerce\Bundle\OrderBundle\DataFixtures\ORM\LoadOrderStatusGroupData: 41
        WellCommerce\Bundle\OrderBundle\DataFixtures\ORM\LoadOrderStatusData: 42
        WellCommerce\Bundle\ClientBundle\DataFixtures\ORM\LoadClientGroupData: 43
        WellCommerce\Bundle\ShopBundle\DataFixtures\ORM\LoadShopData: 50
        WellCommerce\Bundle\AdminBundle\DataFixtures\ORM\LoadUserData: 60
        WellCommerce\Bundle\TaxBundle\DataFixtures\ORM\LoadTaxData: 70
        WellCommerce\Bundle\ClientBundle\DataFixtures\ORM\LoadClientData: 90
        WellCommerce\Bundle\UnitBundle\DataFixtures\ORM\LoadUnitData: 110
        WellCommerce\Bundle\ContactBundle\DataFixtures\ORM\LoadContactData: 130
        WellCommerce\Bundle\MediaBundle\DataFixtures\ORM\LoadMediaData: 135
        WellCommerce\Bundle\DelivererBundle\DataFixtures\ORM\LoadDelivererData: 140
        WellCommerce\Bundle\AvailabilityBundle\DataFixtures\ORM\LoadAvailabilityData: 150
        WellCommerce\Bundle\ProducerBundle\DataFixtures\ORM\LoadProducerData: 160
        WellCommerce\Bundle\AttributeBundle\DataFixtures\ORM\LoadAttributeData: 170
        WellCommerce\Bundle\CategoryBundle\DataFixtures\ORM\LoadCategoryData: 180
        WellCommerce\Bundle\ProductStatusBundle\DataFixtures\ORM\LoadProductStatusData: 190
        WellCommerce\Bundle\ProductBundle\DataFixtures\ORM\LoadProductData: 200
        WellCommerce\Bundle\LayoutBundle\DataFixtures\ORM\LoadLayoutBoxData: 210
        WellCommerce\Bundle\ShippingBundle\DataFixtures\ORM\LoadShippingMethodData: 220
        WellCommerce\Bundle\PaymentBundle\DataFixtures\ORM\LoadPaymentMethodData: 230
        WellCommerce\Bundle\PageBundle\DataFixtures\ORM\LoadPageData: 240
    fixtures_product_limit: 100
    enabled_fixtures:
        WellCommerce\Bundle\AdminBundle\DataFixtures\ORM\LoadAdminMenuData: true
        WellCommerce\Bundle\ThemeBundle\DataFixtures\ORM\LoadThemeData: true
        WellCommerce\Bundle\CompanyBundle\DataFixtures\ORM\LoadCompanyData: true
        WellCommerce\Bundle\CurrencyBundle\DataFixtures\ORM\LoadCurrencyData: true
        WellCommerce\Bundle\LocaleBundle\DataFixtures\ORM\LoadLocaleData: true
        WellCommerce\Bundle\OrderBundle\DataFixtures\ORM\LoadOrderStatusGroupData: true
        WellCommerce\Bundle\OrderBundle\DataFixtures\ORM\LoadOrderStatusData: true
        WellCommerce\Bundle\ShopBundle\DataFixtures\ORM\LoadShopData: true
        WellCommerce\Bundle\AdminBundle\DataFixtures\ORM\LoadUserData: true
        WellCommerce\Bundle\TaxBundle\DataFixtures\ORM\LoadTaxData: true
        WellCommerce\Bundle\ClientBundle\DataFixtures\ORM\LoadClientGroupData: true
        WellCommerce\Bundle\ClientBundle\DataFixtures\ORM\LoadClientData: true
        WellCommerce\Bundle\UnitBundle\DataFixtures\ORM\LoadUnitData: true
        WellCommerce\Bundle\ContactBundle\DataFixtures\ORM\LoadContactData: true
        WellCommerce\Bundle\MediaBundle\DataFixtures\ORM\LoadMediaData: true
        WellCommerce\Bundle\DelivererBundle\DataFixtures\ORM\LoadDelivererData: true
        WellCommerce\Bundle\AvailabilityBundle\DataFixtures\ORM\LoadAvailabilityData: true
        WellCommerce\Bundle\ProducerBundle\DataFixtures\ORM\LoadProducerData: true
        WellCommerce\Bundle\AttributeBundle\DataFixtures\ORM\LoadAttributeData: true
        WellCommerce\Bundle\CategoryBundle\DataFixtures\ORM\LoadCategoryData: true
        WellCommerce\Bundle\ProductStatusBundle\DataFixtures\ORM\LoadProductStatusData: true
        WellCommerce\Bundle\ProductBundle\DataFixtures\ORM\LoadProductData: true
        WellCommerce\Bundle\LayoutBundle\DataFixtures\ORM\LoadLayoutBoxData: true
        WellCommerce\Bundle\ShippingBundle\DataFixtures\ORM\LoadShippingMethodData: true
        WellCommerce\Bundle\PaymentBundle\DataFixtures\ORM\LoadPaymentMethodData: true
        WellCommerce\Bundle\PageBundle\DataFixtures\ORM\LoadPageData: true
    knp.doctrine_behaviors.blameable_listener.user_entity: WellCommerce\AdminBundle\Entity\User

well_commerce_app:
    configuration:
        dimension:
            orm:
                mapping: "@WellCommerceAppBundle/Resources/config/doctrine/Dimension.orm.yml"
                entity: WellCommerce\Bundle\AppBundle\Entity\Dimension
        discountable_price:
            orm:
                factory: WellCommerce\Bundle\AppBundle\Factory\DiscountablePriceFactory
                mapping: "@WellCommerceAppBundle/Resources/config/doctrine/DiscountablePrice.orm.yml"
                entity: WellCommerce\Bundle\AppBundle\Entity\DiscountablePrice
        mailer_configuration:
            orm:
                mapping: "@WellCommerceAppBundle/Resources/config/doctrine/MailerConfiguration.orm.yml"
                entity: WellCommerce\Bundle\AppBundle\Entity\MailerConfiguration
        meta:
            orm:
                mapping: "@WellCommerceAppBundle/Resources/config/doctrine/Meta.orm.yml"
                entity: WellCommerce\Bundle\AppBundle\Entity\Meta
        price:
            orm:
                factory: WellCommerce\Bundle\AppBundle\Factory\PriceFactory
                mapping: "@WellCommerceAppBundle/Resources/config/doctrine/Price.orm.yml"
                entity: WellCommerce\Bundle\AppBundle\Entity\Price
