WellCommerce\Bundle\AppBundle\Entity\ContactTranslation:
    type: entity
    table: contact_translation
    id: {  }
    fields:
        name:
            type: string
            length: 255
            nullable: false
        email:
            type: string
            length: 255
            nullable: false
        phone:
            type: string
            length: 255
            nullable: false
        businessHours:
            type: text
            nullable: true
            column: business_hours
        street:
            type: string
            length: 255
            nullable: true
        streetNo:
            type: string
            length: 255
            nullable: true
            column: street_no
        flatNo:
            type: string
            length: 255
            nullable: true
            column: flat_no
        postCode:
            type: string
            length: 255
            nullable: true
            column: post_code
        province:
            type: string
            length: 255
            nullable: true
        city:
            type: string
            length: 255
            nullable: true
        country:
            type: string
            length: 3
            nullable: true
