well_commerce_order:
    services:
        order:
            auto_services:
                factory: WellCommerce\Bundle\OrderBundle\Factory\OrderFactory
                repository: WellCommerce\Bundle\OrderBundle\Repository\OrderRepository
            orm_configuration:
                mapping: "@WellCommerceOrderBundle/Resources/config/doctrine/Order.orm.yml"
                entity: WellCommerce\Bundle\OrderBundle\Entity\Order
            api_configuration:
                exposed: true
                dataset: order.dataset.admin
                manager: order.manager.admin
        order_product:
            auto_services:
                factory: WellCommerce\Bundle\OrderBundle\Factory\OrderProductFactory
                repository: WellCommerce\Bundle\OrderBundle\Repository\OrderProductRepository
            orm_configuration:
                mapping: "@WellCommerceOrderBundle/Resources/config/doctrine/OrderProduct.orm.yml"
                entity: WellCommerce\Bundle\OrderBundle\Entity\OrderProduct
        order_status:
            auto_services:
                factory: WellCommerce\Bundle\OrderBundle\Factory\OrderStatusFactory
                repository: WellCommerce\Bundle\OrderBundle\Repository\OrderStatusRepository
            orm_configuration:
                mapping: "@WellCommerceOrderBundle/Resources/config/doctrine/OrderStatus.orm.yml"
                entity: WellCommerce\Bundle\OrderBundle\Entity\OrderStatus
            api_configuration:
                exposed: true
                dataset: order_status.dataset.admin
                manager: order_status.manager.admin
        order_status_history:
            auto_services:
                factory: WellCommerce\Bundle\OrderBundle\Factory\OrderStatusHistoryFactory
                repository: WellCommerce\Bundle\OrderBundle\Repository\OrderStatusHistoryRepository
            orm_configuration:
                mapping: "@WellCommerceOrderBundle/Resources/config/doctrine/OrderStatusHistory.orm.yml"
                entity: WellCommerce\Bundle\OrderBundle\Entity\OrderStatusHistory
        order_status_translation:
            orm_configuration:
                mapping: "@WellCommerceOrderBundle/Resources/config/doctrine/OrderStatusTranslation.orm.yml"
                entity: WellCommerce\Bundle\OrderBundle\Entity\OrderStatusTranslation
        order_status_group:
            auto_services:
                factory: WellCommerce\Bundle\OrderBundle\Factory\OrderStatusGroupFactory
                repository: WellCommerce\Bundle\OrderBundle\Repository\OrderStatusGroupRepository
            orm_configuration:
                mapping: "@WellCommerceOrderBundle/Resources/config/doctrine/OrderStatusGroup.orm.yml"
                entity: WellCommerce\Bundle\OrderBundle\Entity\OrderStatusGroup
            api_configuration:
                exposed: true
                dataset: order_status_group.dataset.admin
                manager: order_status_group.manager.admin
        order_status_group_translation:
            orm_configuration:
                mapping: "@WellCommerceOrderBundle/Resources/config/doctrine/OrderStatusGroupTranslation.orm.yml"
                entity: WellCommerce\Bundle\OrderBundle\Entity\OrderStatusGroupTranslation
        order_total:
            auto_services:
                factory: WellCommerce\Bundle\OrderBundle\Factory\OrderTotalFactory
            orm_configuration:
                mapping: "@WellCommerceOrderBundle/Resources/config/doctrine/OrderTotal.orm.yml"
                entity: WellCommerce\Bundle\OrderBundle\Entity\OrderTotal
        order_total_detail:
            auto_services:
                factory: WellCommerce\Bundle\OrderBundle\Factory\OrderTotalDetailFactory
            orm_configuration:
                mapping: "@WellCommerceOrderBundle/Resources/config/doctrine/OrderTotalDetail.orm.yml"
                entity: WellCommerce\Bundle\OrderBundle\Entity\OrderTotalDetail
        order_summary:
            auto_services:
                factory: WellCommerce\Bundle\OrderBundle\Factory\OrderSummaryFactory
            orm_configuration:
                mapping: "@WellCommerceOrderBundle/Resources/config/doctrine/OrderSummary.orm.yml"
                entity: WellCommerce\Bundle\OrderBundle\Entity\OrderSummary
