WellCommerce\Bundle\ShopBundle\Entity\Shop:
    fields:
        id:
            groups:
                - default
                - shop
        name:
            groups:
                - shop
        url:
            groups:
                - shop
        defaultCountry:
            groups:
                - shop
        defaultCurrency:
            groups:
                - shop
    associations:
        company:
            groups:
                - shop
        clientGroup:
            groups:
                - shop
        theme:
            groups:
                - shop
