WellCommerce\Bundle\ClientBundle\Entity\ClientShippingAddress:
    fields:
        firstName:
            groups:
                - default
                - client_shipping_address
        lastName:
            groups:
                - default
                - client_shipping_address
        line1:
            groups:
                - default
                - client_shipping_address
        line2:
            groups:
                - default
                - client_shipping_address
        postalCode:
            groups:
                - default
                - client_shipping_address
        state:
            groups:
                - default
                - client_shipping_address
        city:
            groups:
                - default
                - client_shipping_address
        country:
            groups:
                - default
                - client_shipping_address
    associations: {  }
    callbacks: {  }
