WellCommerce\Bundle\ClientBundle\Entity\Wishlist:
    fields:
        id:
            groups:
                - default
                - wishlist
        createdAt:
            groups:
                - default
                - wishlist
        updatedAt:
            groups:
                - default
                - wishlist
    associations:
        client:
            groups:
                - wishlist
        product:
            groups:
                - wishlist
    callbacks: {  }
