WellCommerce\Bundle\CategoryBundle\Entity\CategoryRoute:
    type: entity
    cache:
        usage: NONSTRICT_READ_WRITE
    table: route_category
    manyToOne:
        identifier:
            targetEntity: WellCommerce\Bundle\CategoryBundle\Entity\Category
            fetch: LAZY
            joinColumns:
                foreign_id:
                    referencedColumnName: id
                    onDelete: CASCADE
