# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

WellCommerce\Bundle\CategoryBundle\Entity\CategoryTranslation:
    type: entity
    cache:
        usage: NONSTRICT_READ_WRITE
    table: category_translation
    embedded:
        meta:
            class: WellCommerce\Bundle\AppBundle\Entity\Meta
            columnPrefix: meta_
    fields:
        name:
            type: string
            length: 255
            nullable: false
        shortDescription:
            type: text
            column: short_description
            nullable: true
        description:
            type: text
            nullable: true
        slug:
            type: string
            length: 255
            nullable: false
    oneToOne:
        route:
            targetEntity: WellCommerce\Bundle\CategoryBundle\Entity\CategoryRoute
            cascade:
                - remove
                - persist
            fetch: LAZY
            joinColumns:
                route_id:
                    referencedColumnName: id
                    onDelete: CASCADE
