WellCommerce\Bundle\CategoryBundle\Entity\CategoryTranslation:
    type: entity
    table: category_translation
    embedded:
        meta:
            class: WellCommerce\Bundle\CoreBundle\Entity\Meta
            columnPrefix: meta_
    fields:
        name:
            type: string
            length: 255
            nullable: false
        shortDescription:
            type: text
            column: short_description
            nullable: true
        description:
            type: text
            nullable: true
        slug:
            type: string
            length: 255
            nullable: false
    oneToOne:
        route:
            targetEntity: WellCommerce\Bundle\CategoryBundle\Entity\CategoryRoute
            cascade:
                - remove
                - persist
            fetch: LAZY
            joinColumns:
                route_id:
                    referencedColumnName: id
                    onDelete: CASCADE
