# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

doctrine_migrations:
    dir_name:   %kernel.root_dir%/sql/migrations
    namespace:  WellCommerce\Migration
    table_name: migration
    name: WellCommerce Migrations

knp_doctrine_behaviors:
    blameable:      true
    geocodable:     false
    loggable:       false
    sluggable:      false
    soft_deletable: false
    timestampable:  true
    translatable:   true

doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        server_version: %doctrine.server_version%
    orm:
        auto_generate_proxy_classes: false
        entity_managers:
            default:
                query_cache_driver:
                    type: service
                    id: doctrine.cache
                metadata_cache_driver:
                    type: service
                    id: doctrine.cache
                result_cache_driver:
                    type: service
                    id: doctrine.cache
                auto_mapping: false
                dql:
                    string_functions:
                        CONCAT_WS: DoctrineExtensions\Query\Mysql\ConcatWs
                        GROUP_CONCAT: DoctrineExtensions\Query\Mysql\GroupConcat
                        IF_ELSE: DoctrineExtensions\Query\Mysql\IfElse
                        DAY: DoctrineExtensions\Query\Mysql\Day
                        MONTH: DoctrineExtensions\Query\Mysql\Month
                        QUARTER: DoctrineExtensions\Query\Mysql\Quarter
                        YEAR: DoctrineExtensions\Query\Mysql\Year
                        DATE_FORMAT: DoctrineExtensions\Query\Mysql\DateFormat
                        FIELD: DoctrineExtensions\Query\Mysql\Field
                filters:
                    locale:
                        class:   WellCommerce\Bundle\LocaleBundle\Doctrine\ORM\Filter\LocaleFilter
                        enabled: false

