WellCommerce\Bundle\ShippingBundle\Entity\ShippingMethod:
    type: entity
    table: shipping_method
    repositoryClass: WellCommerce\Bundle\ShippingBundle\Repository\ShippingMethodRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        calculator:
            type: string
            length: 64
            nullable: false
        optionsProvider:
            type: string
            length: 64
            nullable: false
            column: options_provider
        enabled:
            type: boolean
            nullable: false
        hierarchy:
            type: integer
            nullable: false
            options:
                default: 0
        countries:
            type: json_array
    manyToOne:
        currency:
            targetEntity: WellCommerce\Bundle\CurrencyBundle\Entity\Currency
            fetch: LAZY
            joinColumns:
                currency_id:
                    referencedColumnName: id
                    onDelete: 'RESTRICT'
        tax:
            targetEntity: WellCommerce\Bundle\TaxBundle\Entity\Tax
            fetch: LAZY
            joinColumns:
                tax_id:
                    referencedColumnName: id
                    onDelete: 'RESTRICT'
    oneToMany:
        costs:
            targetEntity: WellCommerce\Bundle\ShippingBundle\Entity\ShippingMethodCost
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: shippingMethod
            orphanRemoval: true
    manyToMany:
        paymentMethods:
            targetEntity: WellCommerce\Bundle\PaymentBundle\Entity\PaymentMethod
            fetch: LAZY
            mappedBy: shippingMethods
