WellCommerce\Bundle\ShippingBundle\Entity\ShippingMethodCost:
    type: entity
    table: shipping_method_cost
    repositoryClass: WellCommerce\Bundle\ShippingBundle\Repository\ShippingMethodCostRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        rangeFrom:
            type: decimal
            scale: 4
            nullable: false
            precision: 15
            column: range_from
        rangeTo:
            type: decimal
            scale: 4
            nullable: false
            precision: 15
            column: range_to
        cost:
            type: decimal
            scale: 4
            nullable: false
            precision: 15
    manyToOne:
        shippingMethod:
            targetEntity: WellCommerce\Bundle\ShippingBundle\Entity\ShippingMethod
            fetch: LAZY
            inversedBy: costs
            joinColumns:
                shipping_method_id:
                    referencedColumnName: id
                    onDelete: CASCADE
