WellCommerce\ClientBundle\Entity\ClientContactDetails:
    type: embeddable
    fields:
        firstName:
            type: string
            length: 255
            nullable: true
            column: first_name
        lastName:
            type: string
            length: 255
            nullable: true
            column: last_name
        phone:
            type: string
            length: 255
            nullable: true
        secondaryPhone:
            type: string
            length: 255
            nullable: true
            column: secondary_phone
        email:
            type: string
            length: 255
            nullable: true
