WellCommerce\Bundle\AppBundle\Entity\NewsTranslation:
    type: entity
    table: news_translation
    embedded:
        meta:
            class: WellCommerce\Bundle\AppBundle\Entity\Meta
    fields:
        topic:
            type: string
            length: 255
            nullable: false
        summary:
            type: text
            nullable: false
        content:
            type: text
            nullable: false
