WellCommerce\Bundle\AppBundle\Entity\ShippingMethodCost:
    type: entity
    table: shipping_method_cost
    repositoryClass: WellCommerce\Bundle\AppBundle\Repository\ShippingMethodCostRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    embedded:
        cost:
            class: WellCommerce\Bundle\AppBundle\Entity\Price
            columnPrefix: cost_
    fields:
        rangeFrom:
            type: decimal
            scale: 4
            nullable: false
            precision: 15
            column: range_from
        rangeTo:
            type: decimal
            scale: 4
            nullable: false
            precision: 15
            column: range_to
    manyToOne:
        shippingMethod:
            targetEntity: WellCommerce\Bundle\AppBundle\Entity\ShippingMethod
            fetch: LAZY
            inversedBy: costs
            joinColumns:
                shipping_method_id:
                    referencedColumnName: id
                    onDelete: CASCADE
