WellCommerce\Bundle\OrderBundle\Entity\OrderProduct:
    fields:
        id:
            groups:
                - default
                - order_product
        quantity:
            groups:
                - default
                - order_product
        weight:
            groups:
                - default
                - order_product
        buyPrice:
            groups:
                - default
                - order_product
        sellPrice:
            groups:
                - default
                - order_product
        createdAt:
            groups:
                - default
                - order_product
        updatedAt:
            groups:
                - default
                - order_product
    associations:
        order:
            groups:
                - order_product
        product:
            groups:
                - order
                - order_product
        productAttribute:
            groups:
                - order_product
    callbacks: {  }
