WellCommerce\Bundle\PaymentBundle\Entity\PaymentMethod:
    type: entity
    table: payment_method
    repositoryClass: WellCommerce\Bundle\PaymentBundle\Repository\PaymentMethodRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        processor:
            type: string
            length: 64
            nullable: false
        enabled:
            type: boolean
            nullable: false
            options:
                default: true
        hierarchy:
            type: integer
            nullable: false
            options:
                default: 0
    manyToOne:
        defaultOrderStatus:
            targetEntity: WellCommerce\Bundle\OrderBundle\Entity\OrderStatus
            fetch: LAZY
            joinColumns:
            default_order_status_id:
                referencedColumnName: id
                onDelete: 'SET NULL'
    manyToMany:
        shippingMethods:
            targetEntity: WellCommerce\Bundle\ShippingBundle\Entity\ShippingMethod
            fetch: LAZY
            inversedBy: paymentMethods
            joinTable:
                name: payment_method_shipping_method
                joinColumns:
                    -
                        name: payment_method_id
                        nullable: false
                        onDelete: CASCADE
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: shipping_method_id
                        nullable: false
                        onDelete: CASCADE
                        referencedColumnName: id
