WellCommerce\Bundle\PaymentBundle\Entity\Payment:
    type: entity
    table: payment
    repositoryClass: WellCommerce\Bundle\PaymentBundle\Repository\PaymentRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToOne:
        order:
            targetEntity: WellCommerce\Bundle\SalesBundle\Entity\Order
            inversedBy: payments
            joinColumn:
                name: order_id
                referencedColumnName: id
                onDelete: CASCADE
