WellCommerce\Bundle\ShopBundle\Entity\Shop:
    type: entity
    cache:
        usage: NONSTRICT_READ_WRITE
    table: shop
    repositoryClass: WellCommerce\Bundle\ShopBundle\Repository\ShopRepository
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    embedded:
        mailerConfiguration:
            class: WellCommerce\Bundle\AppBundle\Entity\MailerConfiguration
            columnPrefix: mailer_configuration_
    fields:
        name:
            type: string
            length: 255
            nullable: false
        url:
            type: string
            length: 255
            unique: true
        defaultCountry:
            type: string
            length: 3
            nullable: true
            column: default_country
        defaultCurrency:
            type: string
            length: 16
            nullable: false
            column: default_currency
    manyToOne:
        company:
            targetEntity: WellCommerce\Bundle\CompanyBundle\Entity\Company
            fetch: LAZY
            joinColumns:
                company_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
        theme:
            targetEntity: WellCommerce\Bundle\ThemeBundle\Entity\ThemeInterface
            fetch: LAZY
            joinColumns:
                theme_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
        clientGroup:
            targetEntity: WellCommerce\Bundle\ClientBundle\Entity\ClientGroup
            fetch: LAZY
            joinColumns:
                client_group_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
