WellCommerce\Bundle\AppBundle\Entity\Media:
    type: entity
    table: media
    repositoryClass: WellCommerce\Bundle\AppBundle\Repository\MediaRepository
    id:
        id:
            type: integer
            nullable: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 255
            nullable: false
        path:
            type: string
            length: 255
            nullable: true
        extension:
            type: string
            length: 12
            nullable: true
        mime:
            type: string
            length: 64
            nullable: true
        size:
            type: string
            length: 12
            nullable: true
    lifecycleCallbacks:
        prePersist:
            - preUpload
        preUpdate:
            - preUpload
