WellCommerce\AppBundle\Entity\Role:
    type: entity
    table: roles
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            scale: 0
            length: 30
            unique: false
            nullable: false
            precision: 0
        role:
            type: string
            scale: 0
            length: 20
            unique: true
            nullable: false
            precision: 0
    manyToMany:
        users:
            targetEntity: WellCommerce\AppBundle\Entity\User
            cascade: {  }
            fetch: LAZY
            mappedBy: roles
            inversedBy: null
            joinTable: {  }
            orderBy: null
    lifecycleCallbacks: {  }
