# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

WellCommerce\Bundle\AttributeBundle\Entity\AttributeValue:
    fields:
        id:
            groups:
                - default
                - attribute_value
        createdAt:
            groups:
                - default
                - attribute_value
        updatedAt:
            groups:
                - default
                - attribute_value
        createdBy:
            groups: {  }
        updatedBy:
            groups: {  }
        deletedBy:
            groups: {  }
    associations:
        attribute:
            groups:
                - attribute_value
        productAttributeValues:
            groups:
                - attribute_value
        translations:
            groups:
                - attribute_value
    callbacks: {  }
