WellCommerce\Bundle\ProducerBundle\Entity\Producer:
    type: entity
    cache:
        usage: NONSTRICT_READ_WRITE
    table: producer
    repositoryClass: WellCommerce\Bundle\ProducerBundle\Repository\ProducerRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    oneToMany:
        products:
            targetEntity: WellCommerce\Bundle\ProductBundle\Entity\Product
            fetch: LAZY
            mappedBy: producer
    manyToMany:
        deliverers:
            targetEntity: WellCommerce\Bundle\DelivererBundle\Entity\Deliverer
            inversedBy: producers
            joinTable:
                name: producer_deliverer
                joinColumns:
                    -
                        name: producer_id
                        nullable: false
                        onDelete: CASCADE
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: deliverer_id
                        nullable: false
                        onDelete: CASCADE
                        referencedColumnName: id
        shops:
            targetEntity: WellCommerce\Bundle\ShopBundle\Entity\ShopInterface
            fetch: LAZY
            joinTable:
                name: shop_producer
                joinColumns:
                    -
                        name: producer_id
                        nullable: false
                        onDelete: CASCADE
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: shop_id
                        nullable: false
                        onDelete: CASCADE
                        referencedColumnName: id
    manyToOne:
        photo:
            targetEntity: WellCommerce\Bundle\MediaBundle\Entity\Media
            fetch: LAZY
            joinColumns:
                photo_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
