WellCommerce\Bundle\ProducerBundle\Entity\ProducerRoute:
    type: entity
    cache:
        usage: NONSTRICT_READ_WRITE
    table: route_producer
    manyToOne:
        identifier:
            targetEntity: WellCommerce\Bundle\ProducerBundle\Entity\Producer
            fetch: LAZY
            joinColumns:
                foreign_id:
                    referencedColumnName: id
                    onDelete: CASCADE
