WellCommerce\Bundle\ProducerBundle\Entity\ProducerTranslation:
    type: entity
    table: producer_translation
    embedded:
        meta:
            class: WellCommerce\Bundle\AppBundle\Entity\Meta
    fields:
        name:
            type: string
            length: 255
        shortDescription:
            type: text
            column: short_description
            nullable: true
        description:
            type: text
            nullable: true
        slug:
            type: string
            length: 255
    oneToOne:
        route:
            targetEntity: WellCommerce\Bundle\ProducerBundle\Entity\ProducerRoute
            cascade:
                - remove
                - persist
            fetch: LAZY
            joinColumns:
                route_id:
                    referencedColumnName: id
                    onDelete: CASCADE
