# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

WellCommerce\Bundle\ClientBundle\Entity\ClientDetails:
    type: embeddable
    fields:
        discount:
            type: decimal
            scale: 2
            nullable: false
            precision: 15
        password:
            type: string
            length: 64
            nullable: false
        username:
            type: string
            length: 60
            unique: false
            nullable: false
        salt:
            type: string
            length: 40
            unique: false
            nullable: false
        resetPasswordHash:
            type: string
            length: 48
            unique: true
            nullable: true
        conditionsAccepted:
            type: boolean
            nullable: false
            column: conditions_accepted
        newsletterAccepted:
            type: boolean
            nullable: false
            column: newsletter_accepted
        legacyPassword:
            type: string
            length: 255
            nullable: true
        legacyPasswordEncoder:
            type: string
            length: 255
            nullable: true