# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

WellCommerce\Bundle\ClientBundle\Entity\ClientGroupTranslation:
    type: entity
    table: client_group_translation
    fields:
        name:
            type: string
            length: 255
            unique: false
            nullable: false
