WellCommerce\Bundle\ClientBundle\Entity\ClientShippingAddress:
    type: embeddable
    fields:
        firstName:
            type: string
            length: 255
            nullable: true
            column: first_name
        lastName:
            type: string
            length: 255
            nullable: true
            column: last_name
        line1:
            type: string
            length: 255
            nullable: true
        line2:
            type: string
            length: 255
            nullable: true
        postalCode:
            type: string
            length: 255
            nullable: true
        state:
            type: string
            length: 255
            nullable: true
        city:
            type: string
            length: 255
            nullable: true
        country:
            type: string
            length: 3
            nullable: true
        copyBillingAddress:
            type: boolean
            nullable: false
            column: copy_billing_address
            options:
                default: true
