well_commerce_routing:
    routers:
        router.default:             100
        routing.dynamic_router:     50
    configuration:
        routing:
            orm:
                factory: WellCommerce\Bundle\RoutingBundle\Factory\RouteFactory
                repository: WellCommerce\Bundle\RoutingBundle\Repository\RouteRepository
                mapping: "@WellCommerceRoutingBundle/Resources/config/doctrine/Route.orm.yml"
                entity: WellCommerce\Bundle\RoutingBundle\Entity\Route


fos_js_routing:
    router: router.default
