front.search.index:
    path: '/search/index/{type},{page},{limit},{orderBy},{orderDir},{priceFrom},{priceTo},{view},{producers},{attributes}'
    defaults:
        _controller: 'search.controller.front:indexAction'
        type: 'product'
        page: '1'
        limit: '12'
        orderBy: score
        orderDir: asc
        priceFrom: '0'
        priceTo: '9999'
        view: grid
        producers: 'null'
        attributes: 'null'
    options:
        expose: true
    requirements:
        index: '[^,]+'
        limit: '\d{1,10}'
        page: '\d{1,10}'
        orderBy: name|finalPrice|score
        orderDir: asc|desc
        priceFrom: '\d{1,10}'
        priceTo: '\d{1,10}'
        view: grid|list
        producers: '[\d+_]+'
        attributes: '[\d+_]+'

front.search.quick:
    path: '/search/quick/{type}'
    defaults:
        _controller: 'search.controller.front:quickSearchAction'
        type: 'product'
    options:
        expose: true
