# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

services:
    search.result.storage:
        class: WellCommerce\Component\Search\Storage\SearchResultStorage

    search.command.reindex:
        class: WellCommerce\Bundle\SearchBundle\Command\ReindexCommand
        arguments: ['%locale%']
        tags:
            - { name: console.command }

    search.type.collection:
        class: Doctrine\Common\Collections\ArrayCollection
        public: false

    search.manager:
        class: WellCommerce\Bundle\SearchBundle\Manager\SearchManager
        arguments: ["@search.type.collection", "@search.result.storage", "@search.adapter"]

    search_request.request_param_converter:
        class: WellCommerce\Bundle\SearchBundle\Request\ParamConverter\SearchRequestParamConverter
        tags:
            - { name: request.param_converter, converter: search_request, priority: 10 }
        arguments: ['@search.manager']
