well_commerce_locale:
    configuration:
        locale:
            orm:
                factory: WellCommerce\Bundle\LocaleBundle\Factory\LocaleFactory
                repository: WellCommerce\Bundle\LocaleBundle\Repository\LocaleRepository
                mapping: "@WellCommerceLocaleBundle/Resources/config/doctrine/Locale.orm.yml"
                entity: WellCommerce\Bundle\LocaleBundle\Entity\Locale
            api:
                exposed: true
                dataset: locale.dataset.admin
                manager: locale.manager
