WellCommerce\Bundle\CatalogBundle\Entity\ProductStatusTranslation:
    type: entity
    table: product_status_translation
    embedded:
        meta:
            class: WellCommerce\Bundle\CoreBundle\Entity\Meta
    fields:
        name:
            type: string
            length: 255
            nullable: false
        cssClass:
            type: string
            length: 255
            nullable: false
            column: css_class
        slug:
            type: string
            length: 255
            nullable: false
    oneToOne:
        route:
            targetEntity: WellCommerce\Bundle\CatalogBundle\Entity\ProductStatusRoute
            cascade:
                - remove
                - persist
            fetch: LAZY
            joinColumns:
                route_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
