doctrine:
    orm:
        resolve_target_entities:
            WellCommerce\Bundle\CouponBundle\Entity\CouponInterface: WellCommerce\Bundle\CouponBundle\Entity\Coupon

well_commerce_coupon:
    configuration:
        coupon:
            orm:
                factory: WellCommerce\Bundle\CouponBundle\Factory\CouponFactory
                repository: WellCommerce\Bundle\CouponBundle\Repository\CouponRepository
                mapping: "@WellCommerceCouponBundle/Resources/config/doctrine/Coupon.orm.yml"
                entity: WellCommerce\Bundle\CouponBundle\Entity\Coupon
            api:
                exposed: true
                dataset: coupon.dataset.admin
                manager: coupon.manager
        coupon_translation:
            orm:
                manager: false
                mapping: "@WellCommerceCouponBundle/Resources/config/doctrine/CouponTranslation.orm.yml"
                entity: WellCommerce\Bundle\CouponBundle\Entity\CouponTranslation

well_commerce_locale:
    copier:
        entities:
            WellCommerce\Bundle\CouponBundle\Entity\CouponTranslation:
                properties:
                    - name
