doctrine:
    orm:
        resolve_target_entities:
            WellCommerce\Bundle\CouponBundle\Entity\CouponInterface: WellCommerce\Bundle\CouponBundle\Entity\Coupon

well_commerce_coupon:
    services:
        coupon:
            auto_services:
                factory: WellCommerce\Bundle\CouponBundle\Factory\CouponFactory
                repository: WellCommerce\Bundle\CouponBundle\Repository\CouponRepository
            orm_configuration:
                mapping: "@WellCommerceCouponBundle/Resources/config/doctrine/Coupon.orm.yml"
                entity: WellCommerce\Bundle\CouponBundle\Entity\Coupon
            api_configuration:
                exposed: true
                dataset: coupon.dataset.admin
                manager: coupon.manager.admin
        coupon_translation:
            orm_configuration:
                mapping: "@WellCommerceCouponBundle/Resources/config/doctrine/CouponTranslation.orm.yml"
                entity: WellCommerce\Bundle\CouponBundle\Entity\CouponTranslation
