WellCommerce\Bundle\RoutingBundle\Entity\Route:
    type: entity
    cache:
        usage: NONSTRICT_READ_WRITE
    table: route
    inheritanceType: JOINED
    discriminatorColumn:
        name: type
        type: string
        fieldName: type
    discriminatorMap:
        route: WellCommerce\Bundle\RoutingBundle\Entity\Route
    repositoryClass: WellCommerce\Bundle\RoutingBundle\Repository\RouteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        path:
            type: string
            unique: false
            nullable: false
        locale:
            type: string
            length: 255
            unique: false
            nullable: false
