# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

WellCommerce\Bundle\AdminBundle\Entity\UserGroup:
    fields:
        id:
            groups:
                - default
                - user_group
        name:
            groups:
                - default
                - user_group
        createdBy:
            groups: {  }
        updatedBy:
            groups: {  }
        deletedBy:
            groups: {  }
    associations:
        permissions:
            groups:
                - user_group
        users:
            groups:
                - user_group
    callbacks: {  }
