# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

WellCommerce\Bundle\AdminBundle\Entity\UserGroupPermission:
    fields:
        id:
            groups:
                - default
                - user_group_permission
        name:
            groups:
                - default
                - user_group_permission
        enabled:
            groups:
                - default
                - user_group_permission
        createdAt:
            groups:
                - default
                - user_group_permission
        updatedAt:
            groups:
                - default
                - user_group_permission
    associations:
        group:
            groups:
                - user_group_permission
    callbacks: {  }
