# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

WellCommerce\Bundle\AdminBundle\Entity\User:
    fields:
        id:
            groups:
                - default
                - user
        firstName:
            groups:
                - default
                - user
        lastName:
            groups:
                - default
                - user
        username:
            groups:
                - default
                - user
        password:
            groups: {  }
        email:
            groups:
                - default
                - user
        salt:
            groups: {  }
        enabled:
            groups:
                - default
                - user
        apiKey:
            groups:
                - default
                - user
        createdAt:
            groups:
                - default
                - user
        updatedAt:
            groups:
                - default
                - user
        createdBy:
            groups: {  }
        updatedBy:
            groups: {  }
        deletedBy:
            groups: {  }
    associations:
        roles:
            groups:
                - user
        groups:
            groups:
                - user
    callbacks: {  }
