WellCommerce\Bundle\DelivererBundle\Entity\Deliverer:
    type: entity
    table: deliverer
    repositoryClass: WellCommerce\Bundle\DelivererBundle\Repository\DelivererRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToMany:
        producers:
            targetEntity: WellCommerce\Bundle\CatalogBundle\Entity\Producer
            fetch: LAZY
            mappedBy: deliverers
