WellCommerce\Bundle\ProductBundle\Entity\Product:
    type: entity
    cache:
        usage: NONSTRICT_READ_WRITE
    table: product
    repositoryClass: WellCommerce\Bundle\ProductBundle\Repository\ProductRepository
    indexes:
        IDX_product_enabled:
            columns: [enabled]
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    embedded:
        buyPrice:
            class: WellCommerce\Bundle\AppBundle\Entity\Price
            columnPrefix: buy_price_
        sellPrice:
            class: WellCommerce\Bundle\AppBundle\Entity\DiscountablePrice
            columnPrefix: sell_price_
        dimension:
            class: WellCommerce\Bundle\AppBundle\Entity\Dimension
            columnPrefix: dimension_
    fields:
        sku:
            type: string
            length: 64
            nullable: false
        stock:
            type: integer
            nullable: false
            options:
                default: 0
        trackStock:
            type: boolean
            nullable: false
            column: track_stock
        weight:
            type: decimal
            scale: 4
            nullable: false
            precision: 15
        packageSize:
            type: decimal
            scale: 4
            nullable: false
            precision: 15
            column: package_size
        enabled:
            type: boolean
            nullable: false
        hierarchy:
            type: integer
            nullable: true
            options:
                default: 0
    manyToOne:
        producer:
            targetEntity: WellCommerce\Bundle\ProducerBundle\Entity\Producer
            fetch: LAZY
            inversedBy: products
            joinColumns:
                producer_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
        unit:
            targetEntity: WellCommerce\Bundle\UnitBundle\Entity\Unit
            fetch: LAZY
            joinColumns:
                unit_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
        availability:
            targetEntity: WellCommerce\Bundle\AvailabilityBundle\Entity\Availability
            fetch: LAZY
            joinColumns:
                availability_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
        buyPriceTax:
            targetEntity: WellCommerce\Bundle\TaxBundle\Entity\Tax
            fetch: LAZY
            joinColumns:
                buy_tax_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
        sellPriceTax:
            targetEntity: WellCommerce\Bundle\TaxBundle\Entity\Tax
            fetch: LAZY
            joinColumns:
                sell_tax_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
        attributeGroup:
            targetEntity: WellCommerce\Bundle\AttributeBundle\Entity\AttributeGroup
            fetch: LAZY
            joinColumns:
                attribute_group_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
        photo:
            targetEntity: WellCommerce\Bundle\MediaBundle\Entity\Media
            fetch: LAZY
            joinColumns:
                photo_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
    manyToMany:
        categories:
            targetEntity: WellCommerce\Bundle\CategoryBundle\Entity\Category
            fetch: LAZY
            inversedBy: products
            joinTable:
                name: category_product
                joinColumns:
                    -
                        name: product_id
                        nullable: false
                        onDelete: CASCADE
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: category_id
                        nullable: false
                        onDelete: CASCADE
                        referencedColumnName: id
        statuses:
            targetEntity: WellCommerce\Bundle\ProductStatusBundle\Entity\ProductStatus
            fetch: LAZY
            inversedBy: products
            joinTable:
                name: product_product_status
                joinColumns:
                    -
                        name: product_id
                        nullable: false
                        onDelete: CASCADE
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: product_status_id
                        nullable: false
                        onDelete: CASCADE
                        referencedColumnName: id
        shops:
            targetEntity: WellCommerce\Bundle\ShopBundle\Entity\ShopInterface
            fetch: LAZY
            joinTable:
                name: shop_product
                joinColumns:
                    -
                        name: product_id
                        nullable: false
                        onDelete: CASCADE
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: shop_id
                        nullable: false
                        onDelete: CASCADE
                        referencedColumnName: id
    oneToMany:
        productPhotos:
            targetEntity: WellCommerce\Bundle\ProductBundle\Entity\ProductPhoto
            cascade:
                - remove
                - persist
            fetch: LAZY
            mappedBy: product
            orphanRemoval: true
        variants:
            targetEntity: WellCommerce\Bundle\ProductBundle\Entity\Variant
            cascade:
                - persist
            fetch: LAZY
            mappedBy: product
            orphanRemoval: true
        reviews:
            targetEntity: WellCommerce\Bundle\ReviewBundle\Entity\Review
            cascade:
              - all
            fetch: LAZY
            mappedBy: product
            orphanRemoval: true
