WellCommerce\Bundle\AppBundle\Entity\ProductAttribute:
    type: entity
    table: product_attribute
    repositoryClass: WellCommerce\Bundle\AppBundle\Repository\ProductAttributeRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    embedded:
        sellPrice:
            class: WellCommerce\Bundle\AppBundle\Entity\DiscountablePrice
            columnPrefix: sell_price_
    fields:
        weight:
            type: decimal
            scale: 4
            nullable: false
            precision: 15
        symbol:
            type: string
            nullable: false
        stock:
            type: integer
            nullable: false
        modifierType:
            type: string
            nullable: false
            column: modifier_type
        modifierValue:
            type: decimal
            scale: 4
            nullable: false
            precision: 15
            column: modifier_value
        hierarchy:
            type: integer
            nullable: false
            options:
                default: 0
    manyToOne:
        product:
            targetEntity: WellCommerce\Bundle\AppBundle\Entity\Product
            fetch: LAZY
            inversedBy: attributes
            joinColumns:
                product_id:
                    referencedColumnName: id
                    onDelete: CASCADE
        availability:
            targetEntity: WellCommerce\Bundle\AppBundle\Entity\Availability
            fetch: LAZY
            joinColumns:
                availability_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
        photo:
            targetEntity: WellCommerce\Bundle\AppBundle\Entity\Media
            fetch: LAZY
            joinColumns:
                photo_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
    manyToMany:
        attributeValues:
            targetEntity: WellCommerce\Bundle\AppBundle\Entity\AttributeValue
            fetch: LAZY
            inversedBy: productAttributeValues
            joinTable:
                name: product_attribute_value
                joinColumns:
                    -
                        name: product_attribute_id
                        nullable: false
                        onDelete: CASCADE
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: attribute_value_id
                        nullable: false
                        onDelete: CASCADE
                        referencedColumnName: id
