WellCommerce\Bundle\MediaBundle\Entity\Media:
    fields:
        id:
            groups:
                - default
                - media
        name:
            groups:
                - default
                - media
        path:
            groups:
                - default
                - media
        extension:
            groups:
                - default
                - media
        mime:
            groups:
                - default
                - media
        size:
            groups:
                - default
                - media
        createdAt:
            groups: {  }
        updatedAt:
            groups: {  }
    associations:
        createdBy:
            groups:
                - media
        updatedBy:
            groups:
                - media
        deletedBy:
            groups:
                - media
    callbacks: {  }
