# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

product.review.report:
    path: /report/{id}
    defaults:
        _controller: 'review.layout_box.controller:reportAction'

product.review.recommendations:
    path: /review/recommendation/{id},{like}
    defaults:
        _controller: 'review.layout_box.controller:recommendationAction'
    options:
        expose: true
