WellCommerce\Bundle\ClientBundle\Entity\Wishlist:
    type: entity
    table: wishlist
    repositoryClass: WellCommerce\Bundle\ClientBundle\Repository\WishlistRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToOne:
        client:
            targetEntity: WellCommerce\Bundle\ClientBundle\Entity\Client
            fetch: LAZY
            inversedBy: wishlist
            joinColumns:
                client_id:
                    referencedColumnName: id
            orphanRemoval: false
        product:
            targetEntity: WellCommerce\Bundle\ProductBundle\Entity\Product
            fetch: LAZY
            joinColumns:
                product_id:
                    referencedColumnName: id
