WellCommerce\Bundle\CouponBundle\Entity\Coupon:
    type: entity
    table: coupon
    repositoryClass: WellCommerce\Bundle\CouponBundle\Repository\CouponRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        code:
            type: string
            nullable: false
            unique: true
        clientUsageLimit:
            type: integer
            nullable: false
            column: client_usage_limit
        globalUsageLimit:
            type: integer
            nullable: false
            column: global_usage_limit
        modifierType:
            type: string
            length: 1
            nullable: false
            column: modifier_type
        modifierValue:
            type: decimal
            scale: 2
            nullable: false
            precision: 15
            column: modifier_value
        validFrom:
            type: datetime
            nullable: true
            column: valid_from
        validTo:
            type: datetime
            nullable: true
            column: valid_to
        currency:
            type: string
            length: 16
            nullable: true
            column: currency
        minimumOrderValue:
            type: decimal
            scale: 2
            nullable: false
            precision: 15
            column: minimum_order_value
        excludePromotions:
            type: boolean
            nullable: false
            options:
                default: true