WellCommerce\Bundle\OrderBundle\Entity\OrderStatusTranslation:
    type: entity
    table: order_status_translation
    fields:
        name:
            type: string
            length: 255
            nullable: false
        defaultComment:
            type: text
            nullable: false
            column: default_comment
