WellCommerce\Bundle\OrderBundle\Entity\OrderProduct:
    type: entity
    table: orders_product
    repositoryClass: WellCommerce\Bundle\OrderBundle\Repository\OrderProductRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    embedded:
        buyPrice:
            class: WellCommerce\Bundle\AppBundle\Entity\Price
            columnPrefix: buy_price_
        sellPrice:
            class: WellCommerce\Bundle\AppBundle\Entity\Price
            columnPrefix: sell_price_
    fields:
        quantity:
            type: integer
            nullable: false
        weight:
            type: decimal
            scale: 4
            nullable: false
            precision: 15
        options:
            type: json_array
    manyToOne:
        order:
            targetEntity: WellCommerce\Bundle\OrderBundle\Entity\Order
            fetch: LAZY
            inversedBy: products
            joinColumns:
                order_id:
                    referencedColumnName: id
                    onDelete: CASCADE
        product:
            targetEntity: WellCommerce\Bundle\ProductBundle\Entity\Product
            fetch: LAZY
            joinColumns:
                product_id:
                    referencedColumnName: id
                    onDelete: RESTRICT
        variant:
            targetEntity: WellCommerce\Bundle\ProductBundle\Entity\Variant
            fetch: LAZY
            joinColumns:
                variant_id:
                    referencedColumnName: id
                    onDelete: RESTRICT
