WellCommerce\Bundle\OrderBundle\Entity\Order:
    type: entity
    cache:
        usage: NONSTRICT_READ_WRITE
    table: orders
    repositoryClass: WellCommerce\Bundle\OrderBundle\Repository\OrderRepository
    indexes:
        IDX_orders_number:
            columns: [number]
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    embedded:
        productTotal:
            class: WellCommerce\Bundle\OrderBundle\Entity\OrderProductTotal
            columnPrefix: product_total_
        summary:
            class: WellCommerce\Bundle\OrderBundle\Entity\OrderSummary
            columnPrefix: summary_
        billingAddress:
            class: WellCommerce\Bundle\ClientBundle\Entity\ClientBillingAddress
            columnPrefix: billing_address_
        shippingAddress:
            class: WellCommerce\Bundle\ClientBundle\Entity\ClientShippingAddress
            columnPrefix: shipping_address_
        clientDetails:
            class: WellCommerce\Bundle\ClientBundle\Entity\ClientDetails
            columnPrefix: client_details_
        contactDetails:
            class: WellCommerce\Bundle\ClientBundle\Entity\ClientContactDetails
            columnPrefix: contact_details_
    fields:
        confirmed:
            type: boolean
            nullable: false
        number:
            type: string
            length: 32
            nullable: true
        sessionId:
            type: string
            nullable: false
            column: session_id
        currency:
            type: string
            length: 16
            nullable: false
            column: currency
        currencyRate:
            type: float
            nullable: false
            column: currency_rate
        comment:
            type: string
            length: 1000
            nullable: false
        shippingMethodOption:
            type: string
            length: 255
            nullable: true
        conditionsAccepted:
            type: boolean
            nullable: false
            column: conditions_accepted
            options:
                default: true
    oneToMany:
        products:
            targetEntity: WellCommerce\Bundle\OrderBundle\Entity\OrderProduct
            cascade:
                - persist
            fetch: LAZY
            mappedBy: order
            orphanRemoval: true
        orderStatusHistory:
            targetEntity: WellCommerce\Bundle\OrderBundle\Entity\OrderStatusHistory
            cascade:
                - persist
            fetch: LAZY
            mappedBy: order
        modifiers:
            indexBy: name
            orderBy: { 'hierarchy': 'ASC' }
            targetEntity: WellCommerce\Bundle\OrderBundle\Entity\OrderModifier
            cascade:
                - persist
            fetch: LAZY
            mappedBy: order
            orphanRemoval: true
        payments:
            targetEntity:  WellCommerce\Bundle\PaymentBundle\Entity\Payment
            mappedBy: order
    manyToOne:
        coupon:
            targetEntity: WellCommerce\Bundle\CouponBundle\Entity\Coupon
            fetch: LAZY
            joinColumns:
                coupon_id:
                    referencedColumnName: id
                    onDelete: SET NULL
        client:
            targetEntity: WellCommerce\Bundle\ClientBundle\Entity\Client
            fetch: LAZY
            joinColumns:
                client_id:
                    referencedColumnName: id
                    onDelete: CASCADE
        paymentMethod:
            targetEntity: WellCommerce\Bundle\PaymentBundle\Entity\PaymentMethod
            fetch: LAZY
            joinColumns:
                payment_method_id:
                    referencedColumnName: id
                    onDelete: RESTRICT
        currentStatus:
            targetEntity: WellCommerce\Bundle\OrderBundle\Entity\OrderStatus
            fetch: LAZY
            joinColumns:
                order_status_id:
                    referencedColumnName: id
                    onDelete: RESTRICT
        shippingMethod:
            targetEntity: WellCommerce\Bundle\ShippingBundle\Entity\ShippingMethod
            fetch: LAZY
            joinColumns:
                shipping_method_id:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
        shop:
            targetEntity: WellCommerce\Bundle\ShopBundle\Entity\ShopInterface
            fetch: LAZY
            joinColumns:
                shop_id:
                    referencedColumnName: id
                    onDelete: RESTRICT
