WellCommerce\Bundle\OrderBundle\Entity\OrderStatus:
    type: entity
    table: order_status
    repositoryClass: WellCommerce\Bundle\OrderBundle\Repository\OrderStatusRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        enabled:
            type: boolean
            nullable: false
        colour:
            type: string
            nullable: true
    manyToOne:
        orderStatusGroup:
            targetEntity: WellCommerce\Bundle\OrderBundle\Entity\OrderStatusGroup
            fetch: LAZY
            joinColumns:
                order_status_group_id:
                    referencedColumnName: id
                    onDelete: CASCADE
