
well_commerce_doctrine:
    configuration:
        attribute:
            factory: WellCommerce\Bundle\AttributeBundle\Factory\AttributeFactory
            repository: WellCommerce\Bundle\AttributeBundle\Repository\AttributeRepository
            mapping: "@WellCommerceAttributeBundle/Resources/config/doctrine/Attribute.orm.yml"
            entity: WellCommerce\Bundle\AttributeBundle\Entity\Attribute
        attribute_translation:
            manager: false
            mapping: "@WellCommerceAttributeBundle/Resources/config/doctrine/AttributeTranslation.orm.yml"
            entity: WellCommerce\Bundle\AttributeBundle\Entity\AttributeTranslation
        attribute_group:
            factory: WellCommerce\Bundle\AttributeBundle\Factory\AttributeGroupFactory
            repository: WellCommerce\Bundle\AttributeBundle\Repository\AttributeGroupRepository
            mapping: "@WellCommerceAttributeBundle/Resources/config/doctrine/AttributeGroup.orm.yml"
            entity: WellCommerce\Bundle\AttributeBundle\Entity\AttributeGroup
        attribute_group_translation:
            manager: false
            mapping: "@WellCommerceAttributeBundle/Resources/config/doctrine/AttributeGroupTranslation.orm.yml"
            entity: WellCommerce\Bundle\AttributeBundle\Entity\AttributeGroupTranslation
        attribute_value:
            factory: WellCommerce\Bundle\AttributeBundle\Factory\AttributeValueFactory
            repository: WellCommerce\Bundle\AttributeBundle\Repository\AttributeValueRepository
            mapping: "@WellCommerceAttributeBundle/Resources/config/doctrine/AttributeValue.orm.yml"
            entity: WellCommerce\Bundle\AttributeBundle\Entity\AttributeValue
        attribute_value_translation:
            manager: false
            mapping: "@WellCommerceAttributeBundle/Resources/config/doctrine/AttributeValueTranslation.orm.yml"
            entity: WellCommerce\Bundle\AttributeBundle\Entity\AttributeValueTranslation
