# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

admin.unit.index:
    path: /index
    defaults:
        _controller: 'unit.controller.admin:indexAction'
    options:
        require_admin_permission: unit.index

admin.unit.grid:
    path: /grid
    condition: "request.isXmlHttpRequest()"
    defaults:
        _controller: 'unit.controller.admin:gridAction'
    options:
        expose: true
        require_admin_permission: unit.index

admin.unit.add:
    path: /add
    defaults:
        _controller: 'unit.controller.admin:addAction'
    options:
        require_admin_permission: unit.add

admin.unit.edit:
    path: '/edit/{id}'
    defaults:
        _controller: 'unit.controller.admin:editAction'
    options:
        expose: true
        require_admin_permission: unit.edit
        
admin.unit.delete:
    path: '/delete/{id}'
    defaults:
        _controller: 'unit.controller.admin:deleteAction'
    options:
        expose: true
        require_admin_permission: unit.delete

admin.unit.delete_group:
    path: '/delete_group'
    defaults:
        _controller: 'unit.controller.admin:deleteGroupAction'
    options:
        expose: true
        require_admin_permission: unit.delete
