WellCommerce\Bundle\ReviewBundle\Entity\Review:
    type: entity
    table: review
    repositoryClass: WellCommerce\Bundle\ReviewBundle\Repository\ReviewRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        nick:
            type: string
            nullable: false
        review:
            type: string
            nullable: false
        rating:
            type: integer
            nullable: false
        enabled:
            type: boolean
            nullable: false
    manyToOne:
        product:
            targetEntity: WellCommerce\Bundle\ProductBundle\Entity\Product
            fetch: LAZY
            inversedBy: reviews
            joinColumns:
                product_id:
                    referencedColumnName: id
                    onDelete: CASCADE
