well_commerce_unit:
    configuration:
        unit:
            orm:
                factory: WellCommerce\Bundle\UnitBundle\Factory\UnitFactory
                repository: WellCommerce\Bundle\UnitBundle\Repository\UnitRepository
                mapping: "@WellCommerceUnitBundle/Resources/config/doctrine/Unit.orm.yml"
                entity: WellCommerce\Bundle\UnitBundle\Entity\Unit
            api:
                exposed: true
                dataset: unit.dataset.admin
                manager: unit.manager
        unit_translation:
            orm:
                mapping: "@WellCommerceUnitBundle/Resources/config/doctrine/UnitTranslation.orm.yml"
                entity: WellCommerce\Bundle\UnitBundle\Entity\UnitTranslation
